# Default values for llm-client
replicaCount: 2

image:
  repository: iamvigneshwars/llm-client
  tag: v2
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: userofficetestbot.diamond.ac.uk
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
