apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-client
  labels:
    app: llm-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: llm-client
  template:
    metadata:
      labels:
        app: llm-client
    spec:
      containers:
        - name: llm-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
